hwdec=auto
ytdl-format=bestvideo[vcodec^=avc1]+bestaudio/best
#ytdl-format=bestvideo[vcodec!=?vp9]+bestaudio/best
autofit-larger=90%
stream-buffer-size=1M
loop-file=inf
#profile=high-quality
#video-sync=display-resample

[network-share]
stream-buffer-size=8M
cache=yes
profile-cond = p["user-data/realpath"]:find("^/System/Volumes")
demuxer-max-bytes=1G
