#!/bin/dash

# Get last non-minimized Alacritty window in the current space
alacritty_win=$(yabai -m query --windows --space | jq -r '[.[] | select(.app=="alacritty" and .["is-minimized"]==false) | .id][-1]')

# Create window if needed, otherwise focus last window
if [ "$alacritty_win" = "null" ]; then
    unset SHELL
    LABEL="pid$$"
    yabai -m signal --add event=window_created label="$LABEL" app="^alacritty$" \
     action="yabai -m window \$YABAI_WINDOW_ID --focus && yabai -m signal --remove $LABEL" \
     && /opt/homebrew/bin/alacritty msg create-window || /opt/homebrew/bin/alacritty
else
    yabai -m window "$alacritty_win" --focus
fi
