#!/bin/dash

# Get last non-minimized Ghostty window in the current space
ghostty_win=$(yabai -m query --windows --space | jq -r '[.[] | select((.app | ascii_downcase == "ghostty") and .["is-minimized"]==false) | .id][-1]')

# Create window if needed, otherwise focus last window
if [ "$ghostty_win" = "null" ]; then
    LABEL="pid$$"
    yabai -m signal --add event=window_created label="$LABEL" app="^[Gg]hostty$" \
     action="yabai -m window \$YABAI_WINDOW_ID --focus && yabai -m signal --remove $LABEL" \
    && osascript -e 'tell application "Ghostty" to new window' > /dev/null 2>&1
else
    yabai -m window "$ghostty_win" --focus
fi
