#!/bin/dash

# Get last non-minimized Ghostty window in the current space
ghostty_win=$(yabai -m query --windows --space | jq -r '[.[] | select(.app=="Ghostty" and .["is-minimized"]==false) | .id][-1]')

# Create window if needed, otherwise focus last window
if [ "$ghostty_win" = "null" ]; then
    LABEL="pid$$"
    yabai -m signal --add event=window_created label="$LABEL" app="^Ghostty$" \
     action="yabai -m window \$YABAI_WINDOW_ID --focus && yabai -m signal --remove $LABEL" \
    && osascript <<EOF
tell application "Ghostty"
    if it is running then
        tell application "System Events" to tell process "Ghostty" to click menu item "New Window" of menu "File" of menu bar 1
    else
        activate
    end if
end tell
EOF
else
    yabai -m window "$ghostty_win" --focus
fi
