-- Generic 16-color scheme. RGB comes from the terminal (ANSI 0-15).
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.termguicolors = false
vim.g.colors_name = "ansi"

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

-- 0 black  1 red     2 green    3 yellow
-- 4 blue   5 magenta 6 cyan     7 white
-- 8–15 are the bright counterparts

-- UI: ctermbg omitted = terminal default background
hl("Normal", { ctermfg = 7 })
hl("NormalNC", { ctermfg = 7 })
hl("NormalFloat", { ctermfg = 7, ctermbg = 0 })
hl("FloatBorder", { ctermfg = 8, ctermbg = 0 })
hl("FloatTitle", { ctermfg = 11, ctermbg = 0, bold = true })
hl("WinSeparator", { ctermfg = 8 })
hl("VertSplit", { ctermfg = 8 })
hl("LineNr", { ctermfg = 8 })
hl("LineNrAbove", { ctermfg = 8 })
hl("LineNrBelow", { ctermfg = 8 })
hl("Cursor", { ctermfg = 0, ctermbg = 7 })
hl("lCursor", { ctermfg = 0, ctermbg = 7 })
hl("CursorLine", { ctermbg = 0 })
hl("CursorColumn", { ctermbg = 0 })
hl("CursorLineNr", { ctermfg = 11, ctermbg = 0, bold = true })
hl("CursorLineSign", { ctermbg = 0 })
hl("CursorLineFold", { ctermfg = 8, ctermbg = 0 })
hl("SignColumn", { ctermfg = 8 })
hl("FoldColumn", { ctermfg = 8 })
hl("Folded", { ctermfg = 8, ctermbg = 0 })
hl("ColorColumn", { ctermbg = 0 })
hl("Visual", { reverse = true })
hl("VisualNOS", { reverse = true })
hl("Search", { ctermfg = 0, ctermbg = 11 })
hl("IncSearch", { ctermfg = 0, ctermbg = 3 })
hl("CurSearch", { ctermfg = 0, ctermbg = 3 })
hl("Substitute", { ctermfg = 0, ctermbg = 9 })
hl("MatchParen", { ctermfg = 14, bold = true })
hl("Whitespace", { ctermfg = 8 })
hl("NonText", { ctermfg = 8 })
hl("EndOfBuffer", { ctermfg = 0 })
hl("SpecialKey", { ctermfg = 8 })
hl("Directory", { ctermfg = 12 })
hl("Title", { ctermfg = 11, bold = true })
hl("Question", { ctermfg = 10 })
hl("MoreMsg", { ctermfg = 10 })
hl("ModeMsg", { ctermfg = 7, bold = true })
hl("ErrorMsg", { ctermfg = 9, bold = true })
hl("WarningMsg", { ctermfg = 11 })
hl("MsgArea", { ctermfg = 7 })
hl("WildMenu", { ctermfg = 0, ctermbg = 11, bold = true })
hl("Pmenu", { ctermfg = 7, ctermbg = 0 })
hl("PmenuSel", { ctermfg = 0, ctermbg = 12 })
hl("PmenuSbar", { ctermbg = 0 })
hl("PmenuThumb", { ctermbg = 8 })
hl("PmenuKind", { ctermfg = 13, ctermbg = 0 })
hl("PmenuKindSel", { ctermfg = 0, ctermbg = 12 })
hl("PmenuExtra", { ctermfg = 8, ctermbg = 0 })
hl("PmenuExtraSel", { ctermfg = 0, ctermbg = 12 })
hl("StatusLine", { ctermfg = 7, ctermbg = 0 })
hl("StatusLineNC", { ctermfg = 8, ctermbg = 0 })
hl("TabLine", { ctermfg = 8, ctermbg = 0 })
hl("TabLineFill", { ctermfg = 8 })
hl("TabLineSel", { ctermfg = 7, bold = true })
hl("WinBar", { ctermfg = 8 })
hl("WinBarNC", { ctermfg = 8 })
hl("QuickFixLine", { ctermbg = 0 })
hl("SpellBad", { ctermfg = 9, underline = true })
hl("SpellCap", { ctermfg = 12, underline = true })
hl("SpellLocal", { ctermfg = 14, underline = true })
hl("SpellRare", { ctermfg = 13, underline = true })
hl("Conceal", { ctermfg = 8 })

hl("Comment", { ctermfg = 8, italic = true })
hl("Constant", { ctermfg = 3 })
hl("String", { ctermfg = 10 })
hl("Character", { ctermfg = 10 })
hl("Number", { ctermfg = 3 })
hl("Boolean", { ctermfg = 3 })
hl("Float", { ctermfg = 3 })
hl("Identifier", { ctermfg = 9 })
hl("Function", { ctermfg = 12 })
hl("Statement", { ctermfg = 13 })
hl("Conditional", { ctermfg = 13 })
hl("Repeat", { ctermfg = 13 })
hl("Label", { ctermfg = 13 })
hl("Operator", { ctermfg = 14 })
hl("Keyword", { ctermfg = 13 })
hl("Exception", { ctermfg = 9 })
hl("PreProc", { ctermfg = 11 })
hl("Include", { ctermfg = 12 })
hl("Define", { ctermfg = 13 })
hl("Macro", { ctermfg = 9 })
hl("PreCondit", { ctermfg = 11 })
hl("Type", { ctermfg = 11 })
hl("StorageClass", { ctermfg = 11 })
hl("Structure", { ctermfg = 11 })
hl("Typedef", { ctermfg = 11 })
hl("Special", { ctermfg = 14 })
hl("SpecialChar", { ctermfg = 3 })
hl("Tag", { ctermfg = 9 })
hl("Delimiter", { ctermfg = 8 })
hl("SpecialComment", { ctermfg = 8, italic = true })
hl("Debug", { ctermfg = 9 })
hl("Underlined", { ctermfg = 12, underline = true })
hl("Ignore", { ctermfg = 8 })
hl("Error", { ctermfg = 9 })
hl("Todo", { ctermfg = 11, bold = true })
hl("Added", { ctermfg = 10 })
hl("Changed", { ctermfg = 11 })
hl("Removed", { ctermfg = 9 })

hl("DiffAdd", { ctermfg = 10, ctermbg = 0 })
hl("DiffChange", { ctermfg = 11, ctermbg = 0 })
hl("DiffDelete", { ctermfg = 9, ctermbg = 0 })
hl("DiffText", { ctermfg = 11, ctermbg = 0, bold = true })

hl("DiagnosticError", { ctermfg = 9 })
hl("DiagnosticWarn", { ctermfg = 11 })
hl("DiagnosticInfo", { ctermfg = 12 })
hl("DiagnosticHint", { ctermfg = 14 })
hl("DiagnosticOk", { ctermfg = 10 })
hl("DiagnosticUnderlineError", { ctermfg = 9, underline = true })
hl("DiagnosticUnderlineWarn", { ctermfg = 11, underline = true })
hl("DiagnosticUnderlineInfo", { ctermfg = 12, underline = true })
hl("DiagnosticUnderlineHint", { ctermfg = 14, underline = true })
hl("DiagnosticVirtualTextError", { ctermfg = 9, ctermbg = 0 })
hl("DiagnosticVirtualTextWarn", { ctermfg = 11, ctermbg = 0 })
hl("DiagnosticVirtualTextInfo", { ctermfg = 12, ctermbg = 0 })
hl("DiagnosticVirtualTextHint", { ctermfg = 14, ctermbg = 0 })
hl("LspReferenceText", { ctermbg = 0 })
hl("LspReferenceRead", { ctermbg = 0 })
hl("LspReferenceWrite", { ctermbg = 0 })
hl("LspInlayHint", { ctermfg = 8, italic = true })
hl("LspSignatureActiveParameter", { ctermfg = 3, bold = true })
hl("DiagnosticSignError", { link = "DiagnosticError" })
hl("DiagnosticSignWarn", { link = "DiagnosticWarn" })
hl("DiagnosticSignInfo", { link = "DiagnosticInfo" })
hl("DiagnosticSignHint", { link = "DiagnosticHint" })
hl("DiagnosticSignOk", { link = "DiagnosticOk" })
hl("DiagnosticFloatingError", { link = "DiagnosticError" })
hl("DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
hl("DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
hl("DiagnosticFloatingHint", { link = "DiagnosticHint" })
hl("DiagnosticUnnecessary", { ctermfg = 8 })
hl("DiagnosticDeprecated", { ctermfg = 8, strikethrough = true })

hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.comment", { link = "@comment" })
hl("@lsp.type.decorator", { link = "@attribute" })
hl("@lsp.type.enum", { link = "@type" })
hl("@lsp.type.enumMember", { link = "@constant" })
hl("@lsp.type.event", { link = "@type" })
hl("@lsp.type.function", { link = "@function" })
hl("@lsp.type.interface", { link = "@type" })
hl("@lsp.type.keyword", { link = "@keyword" })
hl("@lsp.type.macro", { link = "Macro" })
hl("@lsp.type.method", { link = "@function.method" })
hl("@lsp.type.modifier", { link = "@keyword" })
hl("@lsp.type.namespace", { link = "@module" })
hl("@lsp.type.number", { link = "@number" })
hl("@lsp.type.operator", { link = "@operator" })
hl("@lsp.type.parameter", { link = "@variable.parameter" })
hl("@lsp.type.property", { link = "@property" })
hl("@lsp.type.regexp", { link = "@string.special" })
hl("@lsp.type.string", { link = "@string" })
hl("@lsp.type.struct", { link = "@type" })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { link = "@type" })
hl("@lsp.type.variable", { link = "@variable" })
hl("@lsp.type.boolean", { link = "@boolean" })
hl("@lsp.type.builtinType", { link = "@type.builtin" })
hl("@lsp.type.escapeSequence", { link = "@string.escape" })
hl("@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hl("@lsp.type.selfKeyword", { link = "@variable.builtin" })
hl("@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hl("@lsp.type.typeAlias", { link = "@type" })
hl("@lsp.type.unresolvedReference", { ctermfg = 9, underline = true })
hl("@lsp.type.lifetime", { link = "@operator" })
hl("@lsp.type.generic", { link = "@variable" })
hl("@lsp.type.deriveHelper", { link = "@attribute" })
hl("@lsp.type.const", { link = "Constant" })
hl("@lsp.type.punctuation", { link = "Delimiter" })
hl("@lsp.type.magicFunction", { link = "@function.builtin" })
hl("@lsp.type.builtinConstant", { link = "@constant.builtin" })
hl("@lsp.mod.deprecated", { ctermfg = 8, strikethrough = true })
hl("@lsp.mod.readonly", { link = "Constant" })
hl("@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hl("@lsp.typemod.variable.static", { link = "@constant" })
hl("@lsp.typemod.variable.readonly", { link = "@constant" })
hl("@lsp.typemod.variable.injected", { link = "@variable" })
hl("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.function.builtin", { link = "@function.builtin" })
hl("@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hl("@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hl("@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hl("@lsp.typemod.keyword.injected", { link = "@keyword" })
hl("@lsp.typemod.string.injected", { link = "@string" })
hl("@lsp.typemod.operator.injected", { link = "@operator" })

hl("@variable", { ctermfg = 7 })
hl("@variable.builtin", { ctermfg = 9 })
hl("@variable.parameter", { ctermfg = 7 })
hl("@variable.member", { ctermfg = 7 })
hl("@constant", { ctermfg = 3 })
hl("@constant.builtin", { ctermfg = 3 })
hl("@constant.macro", { ctermfg = 9 })
hl("@module", { ctermfg = 11 })
hl("@string", { ctermfg = 10 })
hl("@string.escape", { ctermfg = 3 })
hl("@string.special", { ctermfg = 14 })
hl("@character", { ctermfg = 10 })
hl("@number", { ctermfg = 3 })
hl("@boolean", { ctermfg = 3 })
hl("@function", { ctermfg = 12 })
hl("@function.builtin", { ctermfg = 12 })
hl("@function.macro", { ctermfg = 9 })
hl("@function.method", { ctermfg = 12 })
hl("@constructor", { ctermfg = 11 })
hl("@keyword", { ctermfg = 13 })
hl("@keyword.function", { ctermfg = 13 })
hl("@keyword.return", { ctermfg = 13 })
hl("@keyword.operator", { ctermfg = 14 })
hl("@keyword.import", { ctermfg = 12 })
hl("@operator", { ctermfg = 14 })
hl("@punctuation", { ctermfg = 8 })
hl("@punctuation.bracket", { ctermfg = 8 })
hl("@punctuation.delimiter", { ctermfg = 8 })
hl("@punctuation.special", { ctermfg = 14 })
hl("@type", { ctermfg = 11 })
hl("@type.builtin", { ctermfg = 11 })
hl("@property", { ctermfg = 7 })
hl("@attribute", { ctermfg = 11 })
hl("@comment", { ctermfg = 8, italic = true })
hl("@comment.todo", { ctermfg = 11, bold = true })
hl("@comment.error", { ctermfg = 9, bold = true })
hl("@comment.warning", { ctermfg = 3, bold = true })
hl("@comment.note", { ctermfg = 14, bold = true })
hl("@tag", { ctermfg = 9 })
hl("@tag.attribute", { ctermfg = 11 })
hl("@tag.delimiter", { ctermfg = 8 })
hl("@markup.heading", { ctermfg = 11, bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.link", { ctermfg = 12, underline = true })
hl("@markup.link.url", { ctermfg = 14, underline = true })
hl("@markup.raw", { ctermfg = 10 })
hl("@markup.list", { ctermfg = 14 })
hl("@markup.quote", { ctermfg = 8, italic = true })

hl("GitSignsAdd", { ctermfg = 10 })
hl("GitSignsChange", { ctermfg = 11 })
hl("GitSignsDelete", { ctermfg = 9 })
hl("GitSignsAddLn", { ctermbg = 0 })
hl("GitSignsChangeLn", { ctermbg = 0 })
hl("GitSignsDeleteLn", { ctermbg = 0 })

hl("FlashBackdrop", { ctermfg = 8 })
hl("FlashMatch", { ctermfg = 0, ctermbg = 12 })
hl("FlashCurrent", { ctermfg = 0, ctermbg = 3 })
hl("FlashLabel", { ctermfg = 0, ctermbg = 9, bold = true })

hl("SnacksNormal", { ctermfg = 7 })
hl("SnacksNormalNC", { ctermfg = 7 })
hl("SnacksBorder", { ctermfg = 8 })
hl("SnacksTitle", { ctermfg = 11, bold = true })
hl("SnacksIndent", { ctermfg = 0 })
hl("SnacksIndentScope", { ctermfg = 8 })
hl("SnacksDashboardHeader", { ctermfg = 11 })
hl("SnacksDashboardIcon", { ctermfg = 12 })
hl("SnacksDashboardKey", { ctermfg = 3 })
hl("SnacksDashboardDesc", { ctermfg = 8 })
hl("SnacksDashboardFooter", { ctermfg = 8, italic = true })
hl("SnacksDashboardSpecial", { ctermfg = 13 })
hl("SnacksPickerBorder", { ctermfg = 8 })
hl("SnacksPickerTitle", { ctermfg = 11 })
hl("SnacksPickerMatch", { ctermfg = 3, bold = true })
hl("SnacksPickerDir", { ctermfg = 12 })
hl("SnacksPickerFile", { ctermfg = 7 })
hl("SnacksPickerSelected", { ctermfg = 14 })
hl("SnacksNotifierInfo", { ctermfg = 12 })
hl("SnacksNotifierWarn", { ctermfg = 11 })
hl("SnacksNotifierError", { ctermfg = 9 })

hl("BlinkCmpMenu", { ctermfg = 7, ctermbg = 0 })
hl("BlinkCmpMenuBorder", { ctermfg = 8, ctermbg = 0 })
hl("BlinkCmpMenuSelection", { ctermfg = 0, ctermbg = 12 })
hl("BlinkCmpDoc", { ctermfg = 7, ctermbg = 0 })
hl("BlinkCmpDocBorder", { ctermfg = 8, ctermbg = 0 })
hl("BlinkCmpGhostText", { ctermfg = 8 })
hl("BlinkCmpLabel", { ctermfg = 7 })
hl("BlinkCmpLabelMatch", { ctermfg = 3, bold = true })
hl("BlinkCmpKind", { ctermfg = 13 })
hl("BlinkCmpKindFunction", { ctermfg = 12 })
hl("BlinkCmpKindMethod", { ctermfg = 12 })
hl("BlinkCmpKindVariable", { ctermfg = 9 })
hl("BlinkCmpKindField", { ctermfg = 7 })
hl("BlinkCmpKindClass", { ctermfg = 11 })
hl("BlinkCmpKindInterface", { ctermfg = 11 })
hl("BlinkCmpKindModule", { ctermfg = 11 })
hl("BlinkCmpKindKeyword", { ctermfg = 13 })
hl("BlinkCmpKindSnippet", { ctermfg = 10 })
hl("BlinkCmpKindText", { ctermfg = 8 })
hl("BlinkCmpKindConstant", { ctermfg = 3 })
hl("BlinkCmpKindEnum", { ctermfg = 11 })

hl("WhichKey", { ctermfg = 3 })
hl("WhichKeyGroup", { ctermfg = 12 })
hl("WhichKeyDesc", { ctermfg = 7 })
hl("WhichKeySeparator", { ctermfg = 8 })
hl("WhichKeyFloat", { ctermbg = 0 })
hl("WhichKeyBorder", { ctermfg = 8, ctermbg = 0 })
hl("NoiceCmdlinePopup", { ctermfg = 7, ctermbg = 0 })
hl("NoiceCmdlinePopupBorder", { ctermfg = 8, ctermbg = 0 })
hl("NoiceCmdlineIcon", { ctermfg = 12 })
hl("LazyNormal", { ctermfg = 7, ctermbg = 0 })
hl("LazyButton", { ctermfg = 7, ctermbg = 0 })
hl("LazyButtonActive", { ctermfg = 0, ctermbg = 12 })
hl("LazyH1", { ctermfg = 0, ctermbg = 11, bold = true })
hl("MasonHeader", { ctermfg = 0, ctermbg = 11, bold = true })
hl("MasonHighlight", { ctermfg = 12 })

hl("MiniIndentscopeSymbol", { ctermfg = 8 })
hl("MiniIconsAzure", { ctermfg = 12 })
hl("MiniIconsBlue", { ctermfg = 12 })
hl("MiniIconsCyan", { ctermfg = 14 })
hl("MiniIconsGreen", { ctermfg = 10 })
hl("MiniIconsOrange", { ctermfg = 3 })
hl("MiniIconsPurple", { ctermfg = 13 })
hl("MiniIconsRed", { ctermfg = 9 })
hl("MiniIconsYellow", { ctermfg = 11 })
hl("MiniIconsGrey", { ctermfg = 8 })
hl("BufferLineFill", {})
hl("BufferLineBufferSelected", { ctermfg = 7, bold = true })
hl("BufferLineBufferVisible", { ctermfg = 8 })
hl("BufferLineBackground", { ctermfg = 8 })
hl("TroubleNormal", { ctermfg = 7 })
hl("TodoBgTODO", { ctermfg = 0, ctermbg = 11, bold = true })
hl("TodoFgTODO", { ctermfg = 11 })
hl("TodoBgFIX", { ctermfg = 0, ctermbg = 9, bold = true })
hl("TodoFgFIX", { ctermfg = 9 })
hl("TodoBgHACK", { ctermfg = 0, ctermbg = 3, bold = true })
hl("TodoFgHACK", { ctermfg = 3 })
hl("TodoBgNOTE", { ctermfg = 0, ctermbg = 14, bold = true })
hl("TodoFgNOTE", { ctermfg = 14 })
