[window]
dimensions = { columns = 105, lines = 35 }
opacity = 1
option_as_alt = "Both"
resize_increments = true

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 19
offset = { x = 1, y = 0 }

[selection]
save_to_clipboard = true

[hints]
enabled = []

# Source:   iterm
# Theme:    SpaceGray Eighties
# Author:   unknown
# Variant:  dark
# (MODIFIED, 3, 8, fg,selection)

# Default colors
[colors.primary]
background  = '#222222'
foreground  = '#cccccc'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text        = '#15171c'
cursor      = '#bbbbbb'

# Selection colors
[colors.selection]
background  = '#e0e0e0'
text        = '#222222'

# Normal colors
[colors.normal]
black       = '#15171c'
red         = '#ec5f67'
green       = '#81a764'
#yellow      = '#fec254'
yellow      = '#d3a03e'
blue        = '#5486c0'
magenta     = '#bf83c1'
cyan        = '#57c2c1'
white       = '#efece7'

# Bright colors
[colors.bright]
black       = '#999999'
red         = '#ff6973'
green       = '#93d493'
yellow      = '#ffd256'
blue        = '#4d84d1'
magenta     = '#ff55ff'
cyan        = '#83e9e4'
white       = '#ffffff'
