[window]
dimensions = { columns = 133, lines = 42 }
opacity = 0.95
option_as_alt = "Both"
resize_increments = true

[font]
normal = { family = "Hack", style = "Regular" }
size = 18
offset = { x = 1, y = 0 }

[selection]
save_to_clipboard = true

[hints]
enabled = []
