[window]
dimensions = { columns = 105, lines = 35 }
padding = { x = 2, y = 2 }
opacity = 1
option_as_alt = "Both"
resize_increments = true
decorations_theme_variant = "dark"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
#size = 20
offset = { x = 1, y = 0 }

[selection]
save_to_clipboard = true

[hints]
enabled = []

# Theme:    Eighties Black
# Mode:     dark
# Source:   Chris Kempson (http://chriskempson.com)

# Default colors
[colors.primary]
background  = '#000000'
foreground  = '#cccccc'

[colors.cursor]
text        = 'CellBackground'
cursor      = 'CellForeground'

[colors.selection]
text        = 'CellBackground'
background  = 'CellForeground'

# Normal colors
[colors.normal]
black       = '#111111'
red         = '#ee4549'
green       = '#59b259'
yellow      = '#c86131'
blue        = '#3773af'
magenta     = '#b259b2'
cyan        = '#37afaf'
white       = '#cccccc'

# Bright colors
[colors.bright]
black       = '#888888'
red         = '#f2777a'
green       = '#99cc99'
yellow      = '#ffcc66'
blue        = '#6699cc'
magenta     = '#cc99cc'
cyan        = '#66cccc'
white       = '#f2f0ec'
